services:
    - docker

before_install:
    - docker build -t identity404/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true identity404/react-test npm test

after_success: 
    - docker build -t identity404/multi-client ./client
    - docker build -t identity404/multi-nginx ./nginx
    - docker build -t identity404/multi-server ./server
    - docker build -t identity404/multi-worker ./worker
    # Log into the Docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to dockerhub
    - docker push identity404/multi-client
    - docker push identity404/multi-nginx
    - docker push identity404/multi-server
    - docker push identity404/multi-worker